import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    brandName: 'AL AASKA FIT',
    tagline: 'PREMIUM APPAREL MANUFACTURING',
    subtagline: 'BUILT FOR GLOBAL CLOTHING BRANDS',
    ctaQuote: 'Get Quote',
    ctaProducts: 'Explore Products',
    ctaStart: 'Start Your Brand',
    navHome: 'Home',
    navProducts: 'Products',
    navProcess: 'Our Process',
    navPrivateLabel: 'Private Label',
    navBlog: 'Insights',
    navAdmin: 'Dashboard',
    navContact: 'Contact',
    navOurStory: 'Our Story',
    navSustainability: 'Sustainability',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Service',
    footerSitemap: 'Sitemap',
    statsProduced: 'Pieces Produced',
    statsCountries: 'Countries Served',
    statsExperience: 'Years Experience',
    statsClients: 'Clients Worldwide',
    categoryTitle: 'Premium Product Catalog',
    categorySubtitle: 'Explore our customizable blank silhouettes designed for streetwear, gym wear, and luxury fashion.',
    moqLabel: 'MOQ',
    fabricLabel: 'Fabric',
    gsmLabel: 'GSM',
    printLabel: 'Print Options',
    embroideryLabel: 'Embroidery',
    btnDownloadTechPack: 'Download Tech Pack',
    btnBuildQuote: 'Configure Custom Order',
    timelineTitle: 'Our Manufacturing Journey',
    timelineSubtitle: 'From a design sketch to bulk distribution: how we weave luxury grade garments.',
    privateLabelTitle: 'Private Label Customization',
    privateLabelSubtitle: 'Add custom elements to make our blanks uniquely yours. Full OEM and branding solutions.',
    labelNeckLabels: 'Custom Neck Labels',
    descNeckLabels: 'Satin printed tags, heat transfers, or woven tags stitched seamlessly.',
    labelHangTags: 'Hang Tags',
    descHangTags: 'Thick matte black cardboard with gold foil lettering.',
    labelPolyBags: 'Poly Bags',
    descPolyBags: 'Eco-friendly compostable bags with custom brand printing.',
    labelBrandPackaging: 'Brand Packaging',
    descBrandPackaging: 'Rigid magnetic luxury boxes or custom matte mailing boxes.',
    quoteBuilderTitle: 'Advanced Quote Configurator',
    quoteBuilderSubtitle: 'Customize your apparel parameters and receive a factory-direct pricing quote.',
    formProductType: 'Product Type',
    formQuantity: 'Target Quantity',
    formFabric: 'Fabric Composition',
    formGSM: 'Fabric Weight (GSM)',
    formColors: 'Colorways',
    formSizes: 'Size Range',
    formPrinting: 'Printing Method',
    formEmbroidery: 'Embroidery Detail',
    formPackaging: 'Packaging Choice',
    formName: 'Your Full Name',
    formEmail: 'Email Address',
    formPhone: 'Phone / WhatsApp',
    formMessage: 'Additional Instructions',
    btnSubmitQuote: 'Submit Quote Inquiry',
    blogTitle: 'Factory Insights & Fashion Trends',
    blogSubtitle: 'Stay updated with garment tutorials, fabric guides, and streetwear business strategies.',
    contactTitle: 'Get In Touch',
    contactSubtitle: 'Let’s start your production. Connect with our export sales team or visit our factory.',
    locationLabel: 'Factory Location',
    footerRights: 'All Rights Reserved.',
    langSwitcher: 'Language',
    themeToggle: 'Toggle Theme',
    loginTitle: 'Admin Portal Login',
    logoutBtn: 'Logout',
    dashboardWelcome: 'Welcome Back'
  },
  ur: {
    brandName: 'ال عسکہ فٹ',
    tagline: 'پریمیم ملبوسات کی تیاری',
    subtagline: 'عالمی برانڈز کے لئے تیار کردہ',
    ctaQuote: 'قیمت معلوم کریں',
    ctaProducts: 'مصنوعات دیکھیں',
    ctaStart: 'برانڈ شروع کریں',
    navHome: 'ہوم',
    navProducts: 'مصنوعات',
    navProcess: 'طریقہ کار',
    navPrivateLabel: 'پرائیویٹ لیبل',
    navBlog: 'بلاگ',
    navAdmin: 'ڈیش بورڈ',
    navContact: 'رابطہ',
    navOurStory: 'ہماری کہانی',
    navSustainability: 'پائیداری',
    footerPrivacy: 'پرائیویسی پالیسی',
    footerTerms: 'سروس کی شرائط',
    footerSitemap: 'سائٹ میپ',
    statsProduced: 'تیار کردہ ملبوسات',
    statsCountries: 'برآمدی ممالک',
    statsExperience: 'سالہ تجربہ',
    statsClients: 'عالمی گاہک',
    categoryTitle: 'پریمیم مصنوعات کا کیٹلاگ',
    categorySubtitle: 'ہمارے سٹریٹ ویئر، جم ویئر، اور پرتعیش فیشن کے ڈیزائن دریافت کریں۔',
    moqLabel: 'کم از کم آرڈر',
    fabricLabel: 'کپڑا',
    gsmLabel: 'جی ایس ایم',
    printLabel: 'پرنٹ کے طریقے',
    embroideryLabel: 'کڑھائی',
    btnDownloadTechPack: 'ٹیک پیک ڈاؤن لوڈ کریں',
    btnBuildQuote: 'اپنی مرضی کا آرڈر بنائیں',
    timelineTitle: 'ہمارا مینوفیکچرنگ سفر',
    timelineSubtitle: 'ڈیزائن کے خاکے سے لے کر بلک ترسیل تک: ہم پریمیم کپڑے کیسے تیار کرتے ہیں۔',
    privateLabelTitle: 'پرائیویٹ لیبل کسٹمائزیشن',
    privateLabelSubtitle: 'ہمارے کپڑوں کو اپنا بنانے کے لیے کسٹم عناصر شامل کریں۔ مکمل برانڈنگ حل۔',
    labelNeckLabels: 'کسٹم گردن کے لیبل',
    descNeckLabels: 'ساٹن پرنٹڈ، ہیٹ ٹرانسفر، یا بنے ہوئے لیبلز۔',
    labelHangTags: 'ہینگ ٹیگز',
    descHangTags: 'سونے کے ورق کے حروف کے ساتھ موٹی دھاتی کارڈ بورڈ۔',
    labelPolyBags: 'پولی بیگز',
    descPolyBags: 'برانڈ کے نام کے ساتھ ماحول دوست پولی بیگز۔',
    labelBrandPackaging: 'پریمیم پیکیجنگ',
    descBrandPackaging: 'خوبصورت مقناطیسی ڈبے یا کسٹم میلر بکس۔',
    quoteBuilderTitle: 'جدید آرڈر بنانے والا',
    quoteBuilderSubtitle: 'اپنے کپڑے کے معیار کو منتخب کریں اور فیکٹری کی قیمت حاصل کریں۔',
    formProductType: 'مصنوعات کی قسم',
    formQuantity: 'مطلوبہ تعداد',
    formFabric: 'کپڑے کی ساخت',
    formGSM: 'کپڑے کا وزن (GSM)',
    formColors: 'رنگ',
    formSizes: 'سائز کی حد',
    formPrinting: 'پرنٹنگ کا طریقہ',
    formEmbroidery: 'کڑھائی کی تفصیل',
    formPackaging: 'پیکیجنگ کا انتخاب',
    formName: 'آپ کا نام',
    formEmail: 'ای میل ایڈریس',
    formPhone: 'فون / واٹس ایپ',
    formMessage: 'اضافی معلومات',
    btnSubmitQuote: 'درخواست جمع کروائیں',
    blogTitle: 'فیکٹری معلومات اور فیشن ٹرینڈز',
    blogSubtitle: 'کپڑے کی مینوفیکچرنگ اور فیشن بزنس کی گائیڈز پڑھیں۔',
    contactTitle: 'رابطہ کریں',
    contactSubtitle: 'آئیں اپنی پروڈکشن شروع کریں۔ ہمارے سیلز سے رابطہ کریں یا فیکٹری تشریف لائیں۔',
    locationLabel: 'فیکٹری کا پتہ',
    footerRights: 'جملہ حقوق محفوظ ہیں۔',
    langSwitcher: 'زبان',
    themeToggle: 'تھیم تبدیل کریں',
    loginTitle: 'ایڈمن لاگ ان',
    logoutBtn: 'لاگ آؤٹ',
    dashboardWelcome: 'خوش آمدید'
  },
  ar: {
    brandName: 'ال عسقة فيت',
    tagline: 'تصنيع ملابس فاخرة',
    subtagline: 'مصممة لبراندات الملابس العالمية',
    ctaQuote: 'احصل على عرض سعر',
    ctaProducts: 'تصفح المنتجات',
    ctaStart: 'ابدأ علامتك التجارية',
    navHome: 'الرئيسية',
    navProducts: 'المنتجات',
    navProcess: 'خطوات التصنيع',
    navPrivateLabel: 'العلامة الخاصة',
    navBlog: 'المدونة',
    navAdmin: 'لوحة التحكم',
    navContact: 'اتصل بنا',
    navOurStory: 'قصتنا',
    navSustainability: 'الاستدامة',
    footerPrivacy: 'سياسة الخصوصية',
    footerTerms: 'شروط الخدمة',
    footerSitemap: 'خريطة الموقع',
    statsProduced: 'قطعة تم إنتاجها',
    statsCountries: 'دولة نخدمها',
    statsExperience: 'سنوات الخبرة',
    statsClients: 'عملاء حول العالم',
    categoryTitle: 'كتالوج المنتجات الفاخرة',
    categorySubtitle: 'اكتشف قوالب الملابس القابلة للتخصيص لملابس الشارع والرياضة والأزياء الفاخرة.',
    moqLabel: 'أقل كمية للطلب',
    fabricLabel: 'نوع القماش',
    gsmLabel: 'وزن القماش',
    printLabel: 'خيارات الطباعة',
    embroideryLabel: 'التطريز',
    btnDownloadTechPack: 'تحميل ملف المواصفات',
    btnBuildQuote: 'تخصيص طلبك بالكامل',
    timelineTitle: 'رحلة التصنيع لدينا',
    timelineSubtitle: 'من فكرة وتصميم إلى إنتاج ضخم وتوزيع: كيف نصنع الملابس الفاخرة.',
    privateLabelTitle: 'تخصيص العلامة التجارية الخاصة',
    privateLabelSubtitle: 'أضف هويتك الخاصة على ملابسنا الجاهزة. حلول متكاملة للتعبئة والتغليف.',
    labelNeckLabels: 'ملصقات رقبة مخصصة',
    descNeckLabels: 'ملصقات ساتان مطبوعة أو نقل حراري أو منسوجة.',
    labelHangTags: 'بطاقات تعليق مخصصة',
    descHangTags: 'بطاقات من الورق المقوى الفاخر مع طباعة ذهبية بارزة.',
    labelPolyBags: 'أكياس بلاستيكية مخصصة',
    descPolyBags: 'أكياس صديقة للبيئة قابلة للتحلل مع طباعة شعارك.',
    labelBrandPackaging: 'صناديق مغناطيسية فاخرة',
    descBrandPackaging: 'علب فاخرة أو صناديق شحن كرتونية مخصصة لمشروعك.',
    quoteBuilderTitle: 'منشئ عروض الأسعار الذكي',
    quoteBuilderSubtitle: 'حدد تفاصيل طلبك من الأقمشة والتطريز والكمية للحصول على عرض سعر فوري.',
    formProductType: 'نوع المنتج',
    formQuantity: 'الكمية المطلوبة',
    formFabric: 'نوع القماش المفضل',
    formGSM: 'وزن القماش (GSM)',
    formColors: 'الألوان المتاحة',
    formSizes: 'جدول المقاسات',
    formPrinting: 'طريقة الطباعة',
    formEmbroidery: 'تفاصيل التطريز',
    formPackaging: 'نوع التعبئة والتغليف',
    formName: 'الاسم الكامل',
    formEmail: 'البريد الإلكتروني',
    formPhone: 'رقم الهاتف / واتساب',
    formMessage: 'ملاحظات إضافية',
    btnSubmitQuote: 'إرسال طلب التسعير',
    blogTitle: 'أسرار الصناعة وصيحات الموضة',
    blogSubtitle: 'دروس حول تصنيع الملابس، أوزان الأقمشة، وكيفية إطلاق ماركات الأزياء.',
    contactTitle: 'تواصل معنا',
    contactSubtitle: 'فلنبدأ خط الإنتاج الخاص بك. اتصل بفريق المبيعات الدولي أو شرفنا بزيارة المصنع.',
    locationLabel: 'موقع المصنع',
    footerRights: 'جميع الحقوق محفوظة.',
    langSwitcher: 'اللغة',
    themeToggle: 'تغيير المظهر',
    loginTitle: 'تسجيل دخول الإدارة',
    logoutBtn: 'تسجيل الخروج',
    dashboardWelcome: 'مرحباً بك مجدداً'
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(() => {
    return localStorage.getItem('locale') || 'en';
  });

  useEffect(() => {
    const root = window.document.documentElement;
    root.setAttribute('lang', locale);
    
    // Set text direction based on language
    if (locale === 'ur' || locale === 'ar') {
      root.setAttribute('dir', 'rtl');
    } else {
      root.setAttribute('dir', 'ltr');
    }
    
    localStorage.setItem('locale', locale);
  }, [locale]);

  const t = (key) => {
    return translations[locale]?.[key] || translations['en']?.[key] || key;
  };

  const isRTL = locale === 'ur' || locale === 'ar';

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
